export const plans = [
  {
    id: 1,
    name: "Basic",
    price: "1500",
    speed: "5 Mbps",
    features: {
      speeds: "High-speed internet",
      support: "24/7 customer support",
      data: "Unlimited data",
      router: "Basic Wi-Fi router",
    },
    buttonText: "Get Started",
    buttonLink: "#support",
    icon: "fas fa-check",
    iconColor: "text-success",
  },
  {
    id: 2,
    name: "Standard",
    price: "2000",
    speed: "8 Mbps",
    features: {
      speeds: "High-speed internet",
      support: "24/7 customer support",
      data: "Unlimited data",
      router: "Basic Wi-Fi router",
    },
    buttonText: "Get Started",
    buttonLink: "#support",
    icon: "fas fa-check",
    iconColor: "text-success",
  },
  {
    id: 3,
    name: "Premium",
    price: "2500",
    speed: "12 Mbps",
    features: {
      speeds: "High-speed internet",
      support: "24/7 customer support",
      data: "Unlimited data",
      router: "Basic Wi-Fi router",
    },
    buttonText: "Get Started",
    buttonLink: "#support",
    icon: "fas fa-check",
    iconColor: "text-success",
  },
  {
    id: 4,
    name: "Ultimate",
    price: "3000",
    speed: "20 Mbps",
    features: {
      speeds: "High-speed internet",
      support: "24/7 customer support",
      data: "Unlimited data",
      router: "Basic Wi-Fi router",
    },
    buttonText: "Get Started",
    buttonLink: "#support",
    icon: "fas fa-check",
    iconColor: "text-success",
  },
];
